apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: cistest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: cistest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: cloudadc/backend:0.0.5
        name: backend
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 8081
        env:
        - name: APP_DATACENTER_NAME
          value: "TEST"
        - name: APP_VERSION_NUMBER
          value: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
    cis.f5.com/as3-tenant: "cistest"
    cis.f5.com/as3-app: "cistest"
    cis.f5.com/as3-pool: "cistest_app_svc_pool"
  name: app-svc
  namespace: cistest
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  - port: 8081
    name: management
    protocol: TCP
    targetPort: 8081
  selector:
    app: app
  type: ClusterIP
