kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-cis-configmap-arcadia
  namespace: arcadia
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.21.0",
        "id": "f5-cis-configmap-arcadia",
        "arcadia": {
          "class": "Tenant",
          "arcadia_app": {
            "class": "Application",
            "template": "generic",
            "arcadia_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "192.168.200.60"
              ],
              "snat": "self",
              "serviceDownImmediateAction": "reset",
              "virtualPort": 80,
              "persistenceMethods": [{
                "use": "cookie_encryption"
              }],
              "pool": "arcadia_pool"
            },
            "cookie_encryption": {
              "class": "Persist",
              "persistenceMethod": "cookie",
              "encrypt": true,
              "cookieMethod": "insert",
              "passphrase": {
                "ciphertext": "a3RjeGZ5Z2Q=",
                "protected": "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0="
              }
            },
            "arcadia_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "minimumMembersActive": 0,
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
