apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    cis.f5.com/as3-tenant: hubtest01
    cis.f5.com/as3-app: hubtest01
    cis.f5.com/as3-pool: hubtest01_app_svc_pool
  name: app-svc-2
  namespace: hubtest01
spec:
  ports:
  - port: 80
