apiVersion: v1
kind: Pod
metadata:
  name: test-1
spec:
  containers:
  - command:
    - sh
    - -c
    - echo Hello Kubernetes! && sleep 3600
    image: busybox
    name: busybox
  nodeSelector:
    kubernetes.io/hostname: node-1
---
apiVersion: v1
kind: Pod
metadata:
  name: test-2
spec:
  containers:
  - command:
    - sh
    - -c
    - echo Hello Kubernetes! && sleep 3600
    image: busybox
    name: busybox
  nodeSelector:
    kubernetes.io/hostname: node-2
