kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
    stream-snippets: |
      resolver kube-dns.kube-system.svc.cluster.local valid=5s;

      upstream echoserver-tcp {
          zone echoserver-tcp 64k;
          server echoserver-svc.echoserver.svc.cluster.local service=_echoserver._tcp resolve;
      }

      server {
          listen 8877;
          proxy_pass echoserver-tcp;
          status_zone echoserver-tcp;
      }
