kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-test
  namespace: bigip-control-hub
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.18.0",
        "id": "f5-test",
        "cistest": {
          "class": "Tenant",
          "cistest_app-svc-1": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "192.168.200.34"
              ],
              "snat": "auto",
              "virtualPort": 80,
              "pool": "cistest_app-svc-1_pool"
            },
            "cistest_app-svc-1_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": [ ]
              }
              ]
            }
          }
        }
      }
    }
