apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-dns
  name: test-dns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: test-dns
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-dns
  name: test-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-dns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-dns
    spec:
      containers:
      - image: cloudadc/server_hostname:1.0
        name: hostname
        ports:
        - containerPort: 9376
