apiVersion: v1
kind: Service
metadata:
  labels:
    app: echoserver
  name: echoserver
spec:
  ports:
  - port: 8877
    protocol: TCP
    targetPort: 8877
  selector:
    app: echoserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echoserver
  name: echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  strategy: {}
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: cloudadc/echoserver:1.1
        name: echoserver
        ports:
        - containerPort: 8877
