kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods", "configmaps", "events", "ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  resourceNames: ["bigip-login"]
  verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-ctlr-clusterrole
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: bigip-ctlr

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-writerole
rules:
- apiGroups: ["", "extensions"]
  resources: ["events", "ingresses/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-writerole-binding
  namespace: bigip-ctlr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bigip-ctlr-writerole
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: bigip-ctlr
