= 选择 NOSQL 数据库时优先考虑的五件事
:toc: manual

== 背景

关系数据库在大多数企业或组织中具有很长的历史，这是有充分理由的。关系数据库是满足当前业务需求的现有应用系统的基础；它们得到了广泛的工具生态的支持；而且有大量的技术从业者有能力实施和维护这些系统。

但是目前企业或组织越来越多地考虑遗留关系数据库架构的替代方法。在某些情况下，这样做的动机是技术上的，例如需要处理新的，多结构的数据类型，这些数据类型不适合关系数据库的表格数据模型，或者数据规模超出现有系统的容量限制；在另一些情况下，企业或组织考虑替换遗留关系数据库的动机是希望找到可行的替代昂贵的专有数据库软件和硬件的替代方案；还有一种情况是敏捷性或开发速度，因为企业或组织希望更快地适应市场并采用敏捷开发方法，DevOps 和微服务。

开发团队在技术选择过程中具有强大的影响力，这个群体中目前的一些趋势是发现关系型表格结构的数据模型越来越不能更好的满足他们应用的需求，例如：

* 开发人员开发的应用正在创造一些新的，快速变化的数据类型：结构化、半结构化、非结构化、多态的数据，通常这类数据的量比较大；
* 传统十二到十八个月的瀑布式开发周期的时代已经过去了，现在都是小型的团队，采用敏捷的工作方式，快速迭代，每周或每两周都有新代码的上线，甚至每天有多次上线的可能；
* 过去应用的受众有限，目前以服务的方式发布，需要一直在线，可以从很多不同的设备访问，在全球范围内进行扩展，并在用户附近分发数据，以实现低延迟体验，并符合一些数据合规性法规；
* 企业和组织现在正在转向横向扩展架构，使用开源软件，并运行在普通的硬件平台或云计算平台，而不是采用大型单体服务器和存储的基础架构。

与关系数据库相比，许多非表格“NoSQL”数据库具有几个关键特征，包括更灵活的数据模型，更高的可伸缩性和卓越的性能。但是，大多数这些 NoSQL 数据库也舍弃了使关系数据库对过去几代应用程序都非常关键的基础：富查询能力、二级索引和强一致性。实际上，“NoSQL”通常作为所有非表格数据库的总体类别。就像我们将看到的那样，这个术语太过宽泛，定义太松散而无法真正有用。它通常忽略了 NoSQL 数据库在实现灵活性，可伸缩性和性能方面所进行的取舍。

本文我们的目的是帮助您在选择 NOSQL 或非表格数据，这一复杂又快速变化的领域时提供一些建议，我们描述了企业或组织在确定其应用程序和业务的正确选择时应使用的五个关键维度来评估这些数据库。

== 1. 数据模型


== 2. 查询模型

== 3. 一致性和事务模型


== 4. APIs


== 5. 商业支持、社区实力、及避免厂商绑定


== 为什么 MongoDB


== 结论

