apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: nginx-ingress
    cis.f5.com/as3-app: nginx-ingress-app
    cis.f5.com/as3-pool: nginx-ingress-pool
  name: nginx-ingress-svc
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: nginx-ingress
    cis.f5.com/as3-app: nginx-ingress-dashboard-app
    cis.f5.com/as3-pool: nginx-ingress-dashboard-pool
  name: nginx-ingress-dashboard-svc
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    port: 8898
    protocol: TCP
    targetPort: 8898
  selector:
    app: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-f5
  namespace: nginx-ingress
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "nginx-ingress-f5",
        "label": "nginx-ingress-f5",
        "remark": "Nginx Ingress",
        "nginx-ingress": {
          "class": "Tenant",
          "nginx-ingress-app": {
            "class": "Application",
            "template": "generic",
            "nginx_ingress_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "192.168.7.40"
              ],
              "virtualPort": 80,
              "pool": "nginx-ingress-pool"
            },
            "nginx-ingress-pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "nginx-ingress-dashboard-app": {
            "class": "Application",
            "template": "generic",
            "nginx_ingress_dashboard_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "192.168.7.40"
              ],
              "virtualPort": 8080,
              "pool": "nginx-ingress-dashboard-pool"
            },
            "nginx-ingress-dashboard-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8898,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
