##################################
## Test the Ingress Controller
##################################
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-test
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 8898
    targetPort: 8898
    protocol: TCP
    name: monitor
  selector:
    app: nginx-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginxtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: nginxtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: cloudadc/cafe:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: nginxtest
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: coffee
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  namespace: nginxtest
spec:
  rules:
  - host: nginxtest.example.com
    http:
      paths:
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80