kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftest100
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "perftest100",
        "perftest100": {
          "class": "Tenant",
          "perftest100": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.3"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftest100_app_svc_pool"
            },
            "perftest100_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftest101
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "perftest101",
        "perftest101": {
          "class": "Tenant",
          "perftest101": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.4"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftest101_app_svc_pool"
            },
            "perftest101_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftest102
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "perftest102",
        "perftest102": {
          "class": "Tenant",
          "perftest102": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.5"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftest102_app_svc_pool"
            },
            "perftest102_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftest103
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "perftest103",
        "perftest103": {
          "class": "Tenant",
          "perftest103": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.6"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftest103_app_svc_pool"
            },
            "perftest103_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftest104
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "perftest104",
        "perftest104": {
          "class": "Tenant",
          "perftest104": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.7"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftest104_app_svc_pool"
            },
            "perftest104_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
