sleepTime = 1000 * 30
  
var doc = {
   "name": "John Doe",
   "balance": 99.99,
   "content": "XUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKF",
   "code": "SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010",
   "type": "C1001005",
   "count": 945.4712973582698
}

print()
print("Chunk splits start, check the current chunk, it should only has 1 chunk")
print()
sleep(sleepTime);

for (var i = 0; i < 100000; i++) {
   doc.accountNo = i
   db.account.insertOne( doc )
}

print()
print("100k documents be inserted, check the chunk splits")
print()
sleep(sleepTime);

for (var i = 100000; i < 200000; i++) {
   doc.accountNo = i
   db.account.insertOne( doc )
}

print()
print("100k documents be inserted, check the chunk splits")
print()
