apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: nginx-ingress
    cis.f5.com/as3-app: nginx-ingress-app
    cis.f5.com/as3-pool: nginx-ingress-pool
  name: nginx-ingress-svc
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: nginx-ingress
    cis.f5.com/as3-app: nginx-ingress-fintech-app
    cis.f5.com/as3-pool: nginx-ingress-fintech-pool
  name: nginx-ingress-fintech-svc
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress-fintech
  sessionAffinity: None
  type: ClusterIP
