apiVersion: v1
kind: Namespace
metadata:
  name: test02
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    cis.f5.com/as3-tenant: test01
    cis.f5.com/as3-app: test01
    cis.f5.com/as3-pool: test01_app_svc_pool
  name: app-svc
  namespace: test02
spec:
  ports:
  - port: 80
