apiVersion: v1
kind: Namespace
metadata:
  name: cafe01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: cafe01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: cloudadc/cafe:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: cafe01
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: coffee
---
apiVersion: v1
kind: Namespace
metadata:
  name: cafe02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: cafe02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: cloudadc/cafe:1.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz/coffee
            httpHeaders:
            - name: header1
              value: "Active Health Checks"
            - name: header2
              value: "123"
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: cafe02
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: coffee
