apiVersion: v1
kind: Namespace
metadata:
  labels:
    node: test
  name: wsserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wsserver
  name: wsserver
  namespace: wsserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wsserver
  template:
    metadata:
      labels:
        app: wsserver
    spec:
      containers:
      - image: cloudadc/websocket-server:1.0
        name: wsserver
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: wsserver
    cis.f5.com/as3-app: wsserver
    cis.f5.com/as3-pool: wsserver_svc_pool
  name: wsserver-svc
  namespace: wsserver
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: wsserver
  sessionAffinity: None
  type: ClusterIP
