apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
  name: app-1
  namespace: cistest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest
    cis.f5.com/as3-app: cistest_app-svc-1
    cis.f5.com/as3-pool: cistest_app-svc-1_pool
  name: app-svc-1
  namespace: cistest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-2
  name: app-2
  namespace: cistest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest
    cis.f5.com/as3-app: cistest_app-svc-2
    cis.f5.com/as3-pool: cistest_app-svc-2_pool
  name: app-svc-2
  namespace: cistest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-3
  name: app-3
  namespace: cistest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest
    cis.f5.com/as3-app: cistest_app-svc-3
    cis.f5.com/as3-pool: cistest_app-svc-3_pool
  name: app-svc-3
  namespace: cistest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-3
  sessionAffinity: None
  type: ClusterIP
