apiVersion: v1
kind: Namespace
metadata:
  name: test001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-1
  name: app-1
  namespace: test001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-1
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-2
  name: app-2
  namespace: test001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-2
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-3
  name: app-3
  namespace: test001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-3
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-1
    cis.f5.com/as3-app: test001_1
    cis.f5.com/as3-pool: test001_app_1_svc_pool
    cis.f5.com/as3-tenant: test001
  name: app-1-svc
  namespace: test001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    cis.f5.com/as3-app: test001_2
    cis.f5.com/as3-pool: test001_app_2_svc_pool
    cis.f5.com/as3-tenant: test001
  name: app-2-svc
  namespace: test001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-3
    cis.f5.com/as3-app: test001_3
    cis.f5.com/as3-pool: test001_app_3_svc_pool
    cis.f5.com/as3-tenant: test001
  name: app-3-svc
  namespace: test001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-3
  sessionAffinity: None
  type: ClusterIP