apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-1
  name: app-1
  namespace: test003
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-1
    spec:
      containers:
      - image: kylinsoong/backend:0.0.4
        name: backend
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-1
  name: app-1-svc
  namespace: test003
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  sessionAffinity: None
  type: ClusterIP

