var doc = {
   "name": "John Doe",
   "balance": 99.99,
   "content": "XUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKFXUFEBFGSFJSHYSGDJFKFCFGFJBHKH<JDHBFJJRKF",
   "code": "SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010SZZZURYSGFJDHFJFJFHFJFJHSDC10010",
   "type": "C1001005",
   "count": 945.4712973582698
}

for (var i = 0; i < 300000; i++) {
   doc.accountNo = i
   db.account.insertOne( doc )
}
